[package]
name = "zpl-typst"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
typst = { version = "0.14.2", default-features = false }
typst-svg = "0.14.2"
serde = "1"
serde_json = "1"
time = "0.3.37"
